name: Build
on: [push, pull_request]
jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: 'true'
            - name: Install Node.js
              uses: actions/setup-node@v4
            - name: Find msbuild
              uses: microsoft/setup-msbuild@v1.3.1
            - name: Install NuGet
              uses: nuget/setup-nuget@v1.2
            - name: Install dependencies
              run: nuget restore
            - name: Build and package
              run: msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal
